### ISSUE TITLE
storage: Marker not filtering directory listing

### ISSUE THREAD

**Issue by wd256** [joyent/triton-go#156]
The entries returned by DirectoryClient's List function do not appear to change regardless of the Marker set on the ListDirectoryInput instance.

For example, when performing a listing on a directory containing files `a, b, c` and specifying a Marker of 'b', entries for files a, b and c are included in the response. The result I would expect is for the response to contain entries only for b and c.

**Comment by tjcelaya** [comment]
It seems like we're setting the query param to ["manta_path"](https://github.com/joyent/triton-go/blob/master/storage/directory.go#L59) instead of ["marker"](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/client/MantaDirectoryListingIterator.java#L205), I can open a PR for this with a `directory_test.go` and reference this issue.
